# Generated by Django 6.0.6 on 2026-07-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_groups_user_user_permissions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="tg_username",
        ),
        migrations.AddField(
            model_name="user",
            name="tg_chat_id",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="Chat_ID в Телеграм"
            ),
        ),
    ]
